/**
 * DEFINE ENABLE_ANSI_COLORS TO ENABLE COLOR OUTPUT
 */

#ifndef VK_PBR_RENDERER_ANSI_COLOR_DEFS_H
#define VK_PBR_RENDERER_ANSI_COLOR_DEFS_H

#ifdef ENABLE_ANSI_COLORS
#define ANSI_COLOR(CODE) std::cout << "\033[" << CODE << "m";
#else
#define ANSI_COLOR(CODE)
#endif

#define ANSI_COLOR_RESET ANSI_COLOR(0)

#define ANSI_COLOR_RED ANSI_COLOR(31)
#define ANSI_COLOR_GREEN ANSI_COLOR(32)
#define ANSI_COLOR_YELLOW ANSI_COLOR(33)
#define ANSI_COLOR_BLUE ANSI_COLOR(34)
#define ANSI_COLOR_MAGENTA ANSI_COLOR(35)
#define ANSI_COLOR_CYAN ANSI_COLOR(36)
#define ANSI_COLOR_WHITE ANSI_COLOR(37)

#endif //VK_PBR_RENDERER_ANSI_COLOR_DEFS_H
